import dynamic from "next/dynamic";
import {
  Breadcrumb,
  ToolHeader,
  HowItWorks,
  PrivacyNote,
  FaqSection,
  RelatedTools,
  ToolSkeleton,
} from "@/components/ToolScaffold";
import { JsonLd } from "@/components/JsonLd";
import { toolMeta, softwareAppSchema } from "@/lib/seo";

export const metadata = toolMeta({
  title: "Text to Speech — Free Online, No Signup",
  description:
    "Free text to speech online. Paste text and hear it read aloud with natural voices. No signup, no limits, runs entirely in your browser.",
  keywords:
    "text to speech, tts online free, read text aloud, text to voice, text reader online, free text to speech no signup",
  path: "/text/to-speech",
});

const jsonLd = softwareAppSchema({
  name: "Free Text to Speech",
  description:
    "Read any text aloud in your browser using the voices installed on your device.",
  path: "/text/to-speech",
});

const Tool = dynamic(() => import("@/components/tools/text/TextToSpeech"), {
  ssr: false,
  loading: () => <ToolSkeleton />,
});

const faqs = [
  {
    q: "How do I convert text to speech?",
    a: "Paste or type your text, choose a voice, then press Speak. You can adjust the speed and pitch, and pause or stop at any point.",
  },
  {
    q: "Why do I see different voices than someone else?",
    a: "The voices come from your own device, not from us. Windows, macOS, Android and iOS each ship a different set, and some install extra languages on demand. That is also why the same text can sound quite different on a phone and a laptop.",
  },
  {
    q: "Can I download the audio as an MP3?",
    a: "No. The browser's speech engine plays audio directly and does not expose a recordable file, so there is nothing to save. If you need an audio file, record your system output with an audio recorder, or use a dedicated text-to-speech service that provides downloads.",
  },
  {
    q: "Is there a character limit?",
    a: "There is no limit imposed here. Some browsers do stop long passages after several thousand characters, so if playback cuts off early, split the text into a few shorter sections.",
  },
  {
    q: "Does it support languages other than English?",
    a: "Yes, as long as your device has a voice installed for that language. The voice list shows a language code beside each name. If a language you need is missing, adding it in your operating system's speech or accessibility settings will make it appear here.",
  },
  {
    q: "Is my text sent to a server?",
    a: "No. Speech synthesis happens on your device through the browser's built-in engine, so what you paste never leaves your computer or phone.",
  },
];

export default function Page() {
  return (
    <div className="mx-auto max-w-4xl px-4 py-8 sm:px-6">
      <JsonLd data={jsonLd} />
      <Breadcrumb
        section="Text Tools"
        sectionHref="/text-tools"
        current="Text to Speech"
      />
      <ToolHeader
        title="Text to Speech"
        description="Paste any text and hear it read aloud — adjustable speed and pitch, no signup, and nothing uploaded."
      />
      <div className="mt-8">
        <Tool />
      </div>
      <PrivacyNote>
        <span className="font-medium">Your text never leaves your browser.</span>{" "}
        Speech is generated by your device&apos;s own voice engine — no upload,
        no account, no limits.
      </PrivacyNote>
      <HowItWorks
        name="How to convert text to speech"
        steps={[
          "Paste the text you want read aloud",
          "Pick a voice, speed and pitch",
          "Press Speak and listen",
        ]}
      />
      <section className="mt-14">
        <h2 className="font-display text-2xl font-medium text-text-primary">
          About this tool
        </h2>
        <p className="mt-4 text-[15px] leading-relaxed text-text-muted">
          Hearing text read back is one of the fastest ways to catch writing
          that does not work. Clumsy sentences, repeated words and missing
          connectives are easy to skim past on screen and obvious the moment
          they are spoken. It is equally useful for proofreading, for learning
          pronunciation in another language, for following a long article while
          doing something else, and as an accessibility aid for anyone who finds
          reading long passages tiring.
        </p>
        <p className="mt-4 text-[15px] leading-relaxed text-text-muted">
          This uses the speech engine already built into your browser and
          operating system, which has two consequences worth knowing. The good
          one: it is instant, free, unlimited, and nothing you paste is
          transmitted anywhere. The trade-off: the available voices are whatever
          your device provides, and the audio is played rather than produced as
          a downloadable file.
        </p>
        <p className="mt-4 text-[15px] leading-relaxed text-text-muted">
          Working the other way round — turning speech into text — is handled by
          the{" "}
          <a
            href="/audio/transcribe"
            className="text-primary underline decoration-primary/40 underline-offset-2 hover:decoration-primary"
          >
            audio and video transcriber
          </a>
          , which also runs entirely on your device.
        </p>
      </section>
      <FaqSection items={faqs} />
      <RelatedTools currentHref="/text/to-speech" />
    </div>
  );
}
