import { describe, it, expect } from "vitest";
import { readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import {
  linesFromTesseractBlocks,
  recognizedFromTesseractData,
} from "@/lib/ocr/providers/tesseract";
import { analyzePage } from "@/lib/ocr/layout";
import { buildDocument, documentStats } from "@/lib/ocr/document";
import { toPlainText } from "@/lib/ocr/serialize";

/**
 * End-to-end check against a REAL Tesseract run.
 *
 * Every other test in this suite feeds the analysis synthetic geometry that was
 * written by hand, which validates the algorithms but not the assumption they
 * all rest on: that Tesseract's actual output maps onto the normalized model
 * the way `linesFromTesseractBlocks` expects. This is the only test that
 * exercises that seam.
 *
 * It is opt-in via OCR_REAL=1 because it downloads the English traineddata on
 * first run (~15MB) and takes tens of seconds — unacceptable in the default
 * `npm run test:run` and in CI, fine on demand.
 *
 * The fixture is generated by scripts/render-ocr-fixtures.ps1.
 */

const FIXTURES = resolve(__dirname, "../scripts/fixtures");
const FIXTURE = resolve(FIXTURES, "two-column.png");
const INVOICE = resolve(FIXTURES, "invoice-table.png");
const PHOTO = resolve(FIXTURES, "photo.png");
const ENABLED = process.env.OCR_REAL === "1" && existsSync(FIXTURE);

/**
 * Run one image through the whole pipeline with a real Tesseract worker.
 * NB: not named `process` — that shadows the Node global and breaks the
 * `process.env.OCR_REAL` guard above.
 */
async function runFixture(file: string) {
  const { createWorker } = await import("tesseract.js");
  const worker = await createWorker("eng");
  try {
    const { data } = await worker.recognize(readFileSync(file), {}, { blocks: true });
    const recognized = recognizedFromTesseractData(data, 0, 0, 0);
    const page = analyzePage({ ...recognized, width: 1240, height: 900 });
    const doc = buildDocument({ pages: [page], providerId: "tesseract", languages: ["eng"] });
    return { page, doc, text: toPlainText(doc), stats: documentStats(doc) };
  } finally {
    await worker.terminate();
  }
}

// `describe.runIf` keeps the file green (skipped, not failed) when disabled.
describe.runIf(ENABLED)("real Tesseract end-to-end", () => {
  it(
    "reads a two-column page in correct reading order",
    async () => {
      const { createWorker } = await import("tesseract.js");
      const worker = await createWorker("eng");
      try {
        const image = readFileSync(FIXTURE);
        const { data } = await worker.recognize(image, {}, { blocks: true });

        // 1. The seam: does real output map into the model at all?
        const { lines } = linesFromTesseractBlocks(
          data.blocks as Parameters<typeof linesFromTesseractBlocks>[0]
        );
        expect(lines.length).toBeGreaterThan(0);
        expect(lines.every((l) => l.words.length > 0)).toBe(true);
        expect(lines.every((l) => l.bbox.x1 > l.bbox.x0)).toBe(true);

        // 1b. Tesseract reads STRAIGHT ACROSS the gutter in its default
        //     segmentation mode: it returns ~9 full-width lines for an 18-line
        //     two-column page, each containing text from both columns. This
        //     assertion pins that behaviour, because the whole line-splitting
        //     repair exists to handle it — if a future engine or PSM stops
        //     merging, this test should fail loudly rather than silently
        //     exercising a path that no longer matters.
        const merged = lines.filter((l) => l.bbox.x1 - l.bbox.x0 > 900);
        expect(merged.length).toBeGreaterThan(0);

        // 2. Full pipeline.
        const recognized = recognizedFromTesseractData(data, 0, 1240, 900);
        const page = analyzePage(recognized);
        const doc = buildDocument({
          pages: [page],
          providerId: "tesseract",
          languages: ["eng"],
        });
        const text = toPlainText(doc);

        // 3. Columns were actually detected.
        const stats = documentStats(doc);
        expect(stats.columnsMax).toBe(2);

        // 4. THE REGRESSION: markers must appear in reading order, not raster
        //    order. Interleaved output would be A D B E C F.
        const markers = (text.match(/ALPHA|BRAVO|CHARLIE|DELTA|ECHO|FOXTROT/g) ?? []).filter(
          (m, i, a) => a.indexOf(m) === i
        );
        expect(markers).toEqual(["ALPHA", "BRAVO", "CHARLIE", "DELTA", "ECHO", "FOXTROT"]);

        // 5. Sanity: the text is actually readable, not garbage.
        expect(text.toLowerCase()).toContain("quick brown fox");
      } finally {
        await worker.terminate();
      }
    },
    240_000
  );

  it(
    "detects a real invoice table from a real scan",
    async () => {
      if (!existsSync(INVOICE)) return;
      const { page, text } = await runFixture(INVOICE);

      const tables = page.blocks.filter((b) => b.type === "table");
      expect(tables.length).toBeGreaterThan(0);

      const t = tables[0].table!;
      // Three columns of short cells, several rows.
      expect(t.rows.length).toBeGreaterThanOrEqual(4);
      expect(t.confidence).toBeGreaterThan(0.5);

      // Cell text must survive intact, not be smeared into one string.
      const flat = t.rows.flatMap((r) => r.map((c) => c.text.toLowerCase()));
      expect(flat.some((c) => c.includes("widget"))).toBe(true);
      expect(flat.some((c) => c.includes("9.99"))).toBe(true);

      // And the numbers must still be present in the exported text.
      expect(text).toContain("24.50");
    },
    240_000
  );

  it(
    "does not turn an invoice's aligned columns into a two-column text layout",
    async () => {
      // The inverse of the two-column test: short cells in aligned rows must
      // read as ONE column containing a table, not as two text columns.
      if (!existsSync(INVOICE)) return;
      const { stats } = await runFixture(INVOICE);
      expect(stats.columnsMax).toBe(1);
      expect(stats.tables).toBeGreaterThan(0);
    },
    240_000
  );

  it(
    "survives a photograph with little or no text",
    async () => {
      // Robustness, not accuracy: a low-text image must produce a valid page
      // rather than throwing or emitting a malformed model.
      if (!existsSync(PHOTO)) return;
      const { page, doc, stats } = await runFixture(PHOTO);

      expect(["ok", "blank"]).toContain(page.status);
      expect(Array.isArray(page.blocks)).toBe(true);
      // Whatever it read, the model must stay internally consistent.
      for (const b of page.blocks) {
        expect(b.bbox.x1).toBeGreaterThanOrEqual(b.bbox.x0);
        expect(b.confidence).toBeGreaterThanOrEqual(0);
        expect(b.confidence).toBeLessThanOrEqual(100);
      }
      expect(stats.quality.failedPages).toEqual([]);
      expect(doc.metadata.providerId).toBe("tesseract");
    },
    240_000
  );
});
