import type { Metadata } from "next";

export const SITE_URL = "https://www.getfreetoolsai.com";

/** Build consistent per-tool page metadata with an absolute (self-branded) title. */
export function toolMeta({
  title,
  description,
  path,
}: {
  title: string;
  description: string;
  /**
   * Accepted for call-site compatibility but intentionally NOT emitted: the
   * keywords meta tag carries no SEO value and needlessly exposes a keyword list.
   */
  keywords?: string;
  path: string;
}): Metadata {
  const url = `${SITE_URL}${path}`;
  return {
    title: { absolute: title },
    description,
    openGraph: {
      type: "website",
      locale: "en_US",
      url,
      siteName: "GetFreeToolsAI",
      title,
      description,
      // Generated by app/opengraph-image.tsx (referenced explicitly so nested
      // routes get an og:image too — the file convention only scopes to "/").
      images: [
        {
          url: "/opengraph-image",
          width: 1200,
          height: 630,
          alt: "GetFreeToolsAI — Free Online Tools",
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: ["/opengraph-image"],
    },
    alternates: {
      canonical: url,
      languages: { "en-US": url, "x-default": url },
    },
  };
}

/**
 * SoftwareApplication JSON-LD for a tool page.
 *
 * Note: no `aggregateRating` is emitted. Google requires AggregateRating to
 * reflect genuine, on-page reviews; fabricated ratings risk a structured-data
 * manual action and won't show star rich results anyway. Add it back only once
 * a real review system exists. `ratingCount` is accepted but intentionally
 * unused so existing per-tool call sites don't need to change.
 */
/** FAQPage structured data from a list of Q&As. */
export function faqPageSchema(items: { q: string; a: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: items.map((it) => ({
      "@type": "Question",
      name: it.q,
      acceptedAnswer: { "@type": "Answer", text: it.a },
    })),
  };
}

/** BreadcrumbList structured data. Omit `url` on the current (last) crumb. */
export function breadcrumbSchema(crumbs: { name: string; url?: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: crumbs.map((c, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: c.name,
      ...(c.url ? { item: c.url } : {}),
    })),
  };
}

/** BlogPosting (article) structured data for a guide. */
export function articleSchema({
  title,
  description,
  path,
  datePublished,
  dateModified,
  authorName,
}: {
  title: string;
  description: string;
  path: string;
  datePublished: string;
  dateModified: string;
  authorName: string;
}) {
  return {
    "@context": "https://schema.org",
    "@type": "BlogPosting",
    headline: title,
    description,
    image: `${SITE_URL}/opengraph-image`,
    datePublished,
    dateModified,
    author: { "@type": "Person", name: authorName },
    publisher: {
      "@type": "Organization",
      name: "GetFreeToolsAI",
      logo: { "@type": "ImageObject", url: `${SITE_URL}/logo.png` },
    },
    mainEntityOfPage: { "@type": "WebPage", "@id": `${SITE_URL}${path}` },
  };
}

/** HowTo structured data from ordered steps. */
export function howToSchema(name: string, steps: string[]) {
  return {
    "@context": "https://schema.org",
    "@type": "HowTo",
    name,
    step: steps.map((s, i) => ({
      "@type": "HowToStep",
      position: i + 1,
      name: s,
      text: s,
    })),
  };
}

/** ItemList structured data for a category hub. */
export function itemListSchema(
  name: string,
  items: { name: string; href: string }[]
) {
  return {
    "@context": "https://schema.org",
    "@type": "ItemList",
    name,
    numberOfItems: items.length,
    itemListElement: items.map((it, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: it.name,
      url: `${SITE_URL}${it.href}`,
    })),
  };
}

export function softwareAppSchema({
  name,
  description,
  path,
}: {
  name: string;
  description: string;
  path: string;
  /** @deprecated kept for call-site compatibility; not emitted. */
  ratingValue?: string;
  /** @deprecated kept for call-site compatibility; not emitted. */
  ratingCount?: number;
}) {
  return {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    name,
    applicationCategory: "WebApplication",
    operatingSystem: "Any",
    offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
    description,
    url: `${SITE_URL}${path}`,
    featureList: [
      "No signup required",
      "No watermark",
      "No file size limit",
      "Browser-based processing",
      "Files never uploaded to server",
    ],
    softwareVersion: "1.0",
  };
}
