import type { Metadata } from "next";
import { isNoindexed } from "@/lib/noindex";
import { lastmodFor } from "@/lib/lastmod";
import { allSiteTools } from "@/lib/siteTools";

export const SITE_URL = "https://www.getfreetoolsai.com";

/**
 * The full-catalog ItemList. Rendered ONLY by the homepage — never sitewide.
 *
 * This previously lived in the root layout's `@graph`, which put a ~16KB
 * ItemList of every tool into the <head> of all 363 pages (~5.8MB across the
 * site). That is wrong twice over. Semantically, ItemList should describe what
 * *this* page lists — declaring the whole catalog on /pdf/compress blurs that
 * page's primary entity. Practically, it was 16KB of JSON parsed on every page
 * load on a site whose Total Blocking Time is already the main perf problem.
 *
 * Category hubs emit their own scoped list via `itemListSchema()`, so they need
 * nothing from here.
 */
export const catalogItemListSchema = {
  "@context": "https://schema.org",
  "@type": "ItemList",
  name: "Free Online Tools",
  description: "Complete list of free online tools available on GetFreeToolsAI",
  numberOfItems: allSiteTools.length,
  itemListElement: allSiteTools.map((tool, i) => ({
    "@type": "ListItem",
    position: i + 1,
    name: tool.name,
    url: `${SITE_URL}${tool.href}`,
  })),
};

/** Build consistent per-tool page metadata with an absolute (self-branded) title. */
export function toolMeta({
  title,
  description,
  path,
  ownOgImage,
}: {
  title: string;
  description: string;
  /**
   * Accepted for call-site compatibility but intentionally NOT emitted: the
   * keywords meta tag carries no SEO value and needlessly exposes a keyword list.
   */
  keywords?: string;
  path: string;
  /**
   * Set when this route ships its own `opengraph-image` file. Next's file
   * convention does not scope to nested routes, and an explicit
   * `openGraph.images` here would override the route's own image, so the
   * caller has to say which one it wants.
   */
  ownOgImage?: boolean;
}): Metadata {
  const url = `${SITE_URL}${path}`;
  const ogImage = ownOgImage ? `${url}/opengraph-image` : "/opengraph-image";
  return {
    title: { absolute: title },
    description,
    // Withdrawn pages keep `follow`, so they stay useful to visitors and still
    // pass equity to the tools they link to. See lib/noindex.ts for the rule.
    ...(isNoindexed(path) ? { robots: { index: false, follow: true } } : {}),
    openGraph: {
      type: "website",
      locale: "en_US",
      url,
      siteName: "GetFreeToolsAI",
      title,
      description,
      // Generated by app/opengraph-image.tsx (referenced explicitly so nested
      // routes get an og:image too — the file convention only scopes to "/").
      images: [
        {
          url: ogImage,
          width: 1200,
          height: 630,
          alt: title,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [ogImage],
    },
    alternates: {
      canonical: url,
      languages: { "en-US": url, "x-default": url },
    },
  };
}

/**
 * SoftwareApplication JSON-LD for a tool page.
 *
 * Note: no `aggregateRating` is emitted. Google requires AggregateRating to
 * reflect genuine, on-page reviews; fabricated ratings risk a structured-data
 * manual action and won't show star rich results anyway. Add it back only once
 * a real review system exists. `ratingCount` is accepted but intentionally
 * unused so existing per-tool call sites don't need to change.
 */
/** FAQPage structured data from a list of Q&As. */
export function faqPageSchema(items: { q: string; a: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: items.map((it) => ({
      "@type": "Question",
      name: it.q,
      acceptedAnswer: { "@type": "Answer", text: it.a },
    })),
  };
}

/** BreadcrumbList structured data. Omit `url` on the current (last) crumb. */
export function breadcrumbSchema(crumbs: { name: string; url?: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: crumbs.map((c, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: c.name,
      ...(c.url ? { item: c.url } : {}),
    })),
  };
}

/** BlogPosting (article) structured data for a guide. */
export function articleSchema({
  title,
  description,
  path,
  datePublished,
  dateModified,
  authorName,
}: {
  title: string;
  description: string;
  path: string;
  datePublished: string;
  dateModified: string;
  authorName: string;
}) {
  return {
    "@context": "https://schema.org",
    "@type": "BlogPosting",
    headline: title,
    description,
    image: `${SITE_URL}/opengraph-image`,
    datePublished,
    dateModified,
    author: { "@type": "Person", name: authorName },
    publisher: {
      "@type": "Organization",
      name: "GetFreeToolsAI",
      logo: { "@type": "ImageObject", url: `${SITE_URL}/logo.png` },
    },
    mainEntityOfPage: { "@type": "WebPage", "@id": `${SITE_URL}${path}` },
  };
}

/** HowTo structured data from ordered steps. */
export function howToSchema(name: string, steps: string[]) {
  return {
    "@context": "https://schema.org",
    "@type": "HowTo",
    name,
    step: steps.map((s, i) => ({
      "@type": "HowToStep",
      position: i + 1,
      name: s,
      text: s,
    })),
  };
}

/** ItemList structured data for a category hub. */
export function itemListSchema(
  name: string,
  items: { name: string; href: string }[]
) {
  return {
    "@context": "https://schema.org",
    "@type": "ItemList",
    name,
    numberOfItems: items.length,
    itemListElement: items.map((it, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: it.name,
      url: `${SITE_URL}${it.href}`,
    })),
  };
}

export function softwareAppSchema({
  name,
  description,
  path,
  dateModified,
}: {
  name: string;
  description: string;
  path: string;
  /**
   * Freshness signal. Defaults to the honest date from the central `lastmod`
   * registry so it always matches the sitemap's `<lastmod>` for this path.
   */
  dateModified?: string;
  /** @deprecated kept for call-site compatibility; not emitted. */
  ratingValue?: string;
  /** @deprecated kept for call-site compatibility; not emitted. */
  ratingCount?: number;
}) {
  return {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    name,
    applicationCategory: "WebApplication",
    operatingSystem: "Any",
    offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
    description,
    url: `${SITE_URL}${path}`,
    featureList: [
      "No signup required",
      "No watermark",
      "No artificial size cap",
      "Browser-based processing",
      "Files never uploaded to server",
    ],
    softwareVersion: "1.0",
    dateModified: dateModified ?? lastmodFor(path),
  };
}
