import type { Metadata } from "next";

export const SITE_URL = "https://www.getfreetoolsai.com";

/** Build consistent per-tool page metadata with an absolute (self-branded) title. */
export function toolMeta({
  title,
  description,
  keywords,
  path,
}: {
  title: string;
  description: string;
  keywords: string;
  path: string;
}): Metadata {
  const url = `${SITE_URL}${path}`;
  return {
    title: { absolute: title },
    description,
    keywords,
    openGraph: {
      type: "website",
      locale: "en_US",
      url,
      siteName: "GetFreeToolsAI",
      title,
      description,
      // Generated by app/opengraph-image.tsx (referenced explicitly so nested
      // routes get an og:image too — the file convention only scopes to "/").
      images: [
        {
          url: "/opengraph-image",
          width: 1200,
          height: 630,
          alt: "GetFreeToolsAI — Free Online Tools",
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: ["/opengraph-image"],
    },
    alternates: {
      canonical: url,
      languages: { "en-US": url, "x-default": url },
    },
  };
}

/**
 * SoftwareApplication JSON-LD for a tool page.
 *
 * Note: no `aggregateRating` is emitted. Google requires AggregateRating to
 * reflect genuine, on-page reviews; fabricated ratings risk a structured-data
 * manual action and won't show star rich results anyway. Add it back only once
 * a real review system exists. `ratingCount` is accepted but intentionally
 * unused so existing per-tool call sites don't need to change.
 */
export function softwareAppSchema({
  name,
  description,
  path,
}: {
  name: string;
  description: string;
  path: string;
  /** @deprecated kept for call-site compatibility; not emitted. */
  ratingValue?: string;
  /** @deprecated kept for call-site compatibility; not emitted. */
  ratingCount?: number;
}) {
  return {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    name,
    applicationCategory: "WebApplication",
    operatingSystem: "Any",
    offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
    description,
    url: `${SITE_URL}${path}`,
    featureList: [
      "No signup required",
      "No watermark",
      "No file size limit",
      "Browser-based processing",
      "Files never uploaded to server",
    ],
    softwareVersion: "1.0",
  };
}
